# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= tinystr.o tinyxml.o tinyxmlerror.o tinyxmlparser.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}


include $(MAKEPARAM)




